# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aikido in Gent
description: > # this means to ignore newlines until "baseurl:"
  Onze dojo werd opgericht in 2002 door Stefaan Six en is geaffilieerd met
  Ban Sen Juku vzw, de Europese tak van de Osaka Aikikai. Ban Sen Juku staat
  onder leiding van Tomita sensei (8ste dan).
  De vertaling van Ban Sen Juku luidt: \"School der tienduizend stromen\"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aikidogent.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
timezone: BE

sass:
    style: compressed
